#! /usr/bin/env bash

first_name="${BASH_SOURCE[0]}"
actual_name="$(readlink -f "${first_name}")"
local_path="$(dirname "${actual_name}")"

. "${local_path}/logging"

exceptions::Unimplemented() {
    logging::fatal "Unimplemented"
    exit 255
}

