#!/usr/bin/env bash

. $(optionslib --lib)

start_service() {
    logging::info "STARTING RUNNER: ${@}"
}

config_options=

optionslib::parse::description "The demo to end all demos"

optionslib::parse::config "
    long_options=--help short_options=-h action=show_help description='show help options'
    long_options=--config: action=store_var name=config_options description='service configuration' required=true
    long_options=--go: action=command name=start_service description='Do nothing'
"

if ! optionslib::parse::parse_arguments "$@"
then
    exit 255
fi

echo "CONFIG=${config_options}"
